version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    assignees:
      - blck-snwmn
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"
