name: 'Textlint Action'
description: 'Runs textlint on files'
inputs:
  directory:
    description: 'Relative path to directory from `workspace` for scanning files.'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Checkout code'
      uses: actions/checkout@v3

    - name: 'Set up Node.js'
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - uses: reviewdog/action-setup@v1

    - name: 'Install dependencies'
      run: npm ci
      working-directory: ${{ github.action_path }}
      shell: bash

    - name: test
      shell: bash
      run: |
        greet="Hello World!"
        echo "$greet"

    - name: 'Run textlint'
      id: textlint
      working-directory: ${{ github.action_path }}
      shell: bash
      run: |
        echo "output=$(npx textlint -f checkstyle ${{ github.workspace }}/${{ inputs.directory }}/**)" > "$GITHUB_OUTPUT"
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{github.token}}
    
    - name: Reviewdog
      run: |
        echo "${{steps.textlint.outputs.output}}" | reviewdog -f=checkstyle -name="textlint" -reporter=github-pr-check 
      shell: bash