inputs:
  working-directory:
    type: string
    default: .
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version-file: "${{ inputs.working-directory }}/go.mod"