inputs:
  working-directory:
    type: string
    default: .
  config-path:
    type: string
    default: ${{ github.action_path }}/.golangci.yml
runs:
  using: composite
  steps:
    - uses: blck-snwmn/share-workflows/go/setup@main
      with:
        working-directory: ${{inputs.working-directory}}
    - name: test
      run: echo "${{ inputs.config-path }}"
      bash: shell
    - name: test2
      run: echo "${{ github.action_path }}"
      bash: shell
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: --config=${{ inputs.config-path }}
        working-directory: ${{ inputs.working-directory }}
