inputs:
  working-directory:
    type: string
    default: .
  config-path:
    type: string
    required: false
runs:
  using: composite
  steps:
    - uses: blck-snwmn/share-workflows/go/setup@main
      with:
        working-directory: ${{inputs.working-directory}}
    - name: config path
      id: config-path
      run : |
        if [[ -z "${{ inputs.config-path }}" ]]; then
          echo "config path is empty"
          echo "config-path=${{ inputs.working-directory }}/.golangci.yml" >> $GITHUB_OUTPUT
        else
          echo "config path is not empty"
          echo "config-path=${{ inputs.config-path }}" >> $GITHUB_OUTPUT
        fi
      shell: bash
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: --config=${{ steps.config-path.outputs.config-path }}
        working-directory: ${{ inputs.working-directory }}
