name: Example for textlint

on:
  push:
    branches:
      - main
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: blck-snwmn/share-workflows/txt/textlint@main
        with:
            directory: example/textlint