name: Example for textlint

on:
  pull_request:
jobs:
  textlint:
    runs-on: ubuntu-latest
    steps:
      - uses: blck-snwmn/share-workflows/txt/textlint@main
        with:
            directory: example/textlint