name: Example for textlint

on:
  pull_request:
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: blck-snwmn/share-workflows/txt/textlint@feat/add-invalid-json
        with:
            directory: example/textlint