name: Deploy

on: 
  workflow_call:
    inputs:
      working-directory:
        type: string
        default: .
    secrets:
      CF_API_TOKEN:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        uses: cloudflare/wrangler-action@v3.4.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: ${{ inputs.working-directory }}
