name: Go test&lint

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        default: .
      config-path:
        type: string
        required: false
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: blck-snwmn/share-workflows/go/setup@main
        with:
          working-directory: ${{ inputs.working-directory }}
      - name: Run test
        working-directory: ${{ inputs.working-directory }}
        run: |
          go test ./... --shuffle on --parallel 10 --p 10
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: blck-snwmn/share-workflows/go/lint@main
        with:
          working-directory: ${{ inputs.working-directory }}
          config-path: ${{ inputs.config-path }}
